### ISSUE TITLE
1.5.2 Beta / Bad Error Failed to save, there is too many tiles objects

### ISSUE THREAD

**Issue by Sweepr** [Zarby89/ZScreamDungeon#16]
What does that mean, i get that when i move torch objects around in a room and then try to save the ROM.

Altough it seems to be saving the ROM and does not appear to be corrupt

**Comment by Zarby89** [comment]
i have not been able to reproduce that issue, if you have more information about it that would be helpful

**Comment by Sweepr** [comment]
I'll see if i can get some more information.

**Comment by Sweepr** [comment]
Probably due to the fact ROM made with Hyrule Magic, no longer needed so closing.
