### ISSUE TITLE
Hexadecimal room number input gets reversed

### ISSUE THREAD

**Issue by john-champagne** [Zarby89/ZScreamDungeon#65]
Found this bug on 3.2.3

What I am trying to do is open up room 12h (18 decimal). Unfortunately, when I start typing this value into the _Go to room_ window, the cursor moves to the front of the text input, causing the number to get reversed (21h instead of 12h).

### To Reproduce

1. Launch program, open your ROM, etc.
2. Press _Dungeon > Go to Room_
3. A sub window opens. Select the Hexadecimal checkbox.
4. A `0` should now be in the input box.
5. Click the input box and input any two hexadecimal digits.

**Comment by john-champagne** [comment]
Here's an animation of it:

![out](https://github.com/Zarby89/ZScreamDungeon/assets/30150781/e680d67c-9d26-417a-bc50-5a268b114c46)

Trying to enter `56` but it reads it as `65`. Note that I can delete the input and retype it correctly.

**Comment by Zarby89** [comment]
That window is very old haha, that's fixed, that'll be fixed in next release

**Comment by john-champagne** [comment]
Thanks! I pulled the dev branch and ran that; it runs very well!

This is an awesome project. Looking forward to new updates!
